version: '3.3'

services:
  teleconsulta-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teleconsulta-salas
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m
    restart: unless-stopped
    networks:
      - teleconsulta-network

networks:
  teleconsulta-network:
    driver: bridge
